version: "3.9"
services:
  golftracker:
    build: .
    container_name: golftracker-service
    ports:
      - "5005:5005"
    environment:
      - MODEL_PATH=data/best.pt
      - SERVICE_PORT=5005
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    volumes:
      - /data:/data:ro
    restart: unless-stopped


