version: "3.9"
services:
  golftracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golftracker-service
    ports:
      - "5005:5005"
    environment:
      - MODEL_PATH=data/best.pt
      - SERVICE_PORT=5005
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    volumes:
      - ./data:/data:ro
    restart: unless-stopped
    runtime: nvidia
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5005/healthz')"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: golftracker-cloudflared
    restart: unless-stopped
    depends_on:
      golftracker:
        condition: service_healthy
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYjI3MWFkZDVhMTFmNzc1NDJiZTgzY2U3ZGIwMDgxYWQiLCJ0IjoiZDhmN2RlMzAtNDA1NS00M2ZlLTkxYTktOGI5YmZmMDBhZTljIiwicyI6Ik1ETTVZelJpWlRVdFpHTTBPUzAwTWpBNExUa3hOVGd0T1RRMk1tVXpOR0ZpT1RNeSJ9
