version: "3.9"
services:
  golftracker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: golftracker-service-dev
    ports:
      - "5005:5005"
    environment:
      - MODEL_PATH=data/best.pt
      - SERVICE_PORT=5005
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    volumes:
      - ./data:/data:ro
      # 开发模式：挂载代码目录，支持热重载
      - ./app:/app/app:ro
      - ./analyzer:/app/analyzer:ro
      - ./detector:/app/detector:ro
    restart: unless-stopped
    runtime: nvidia
